### PR TITLE
Fix defaultPassword to work properly

### PR DESCRIPTION
**Pull request by Nicell**
Current code fails every time as logMessage.password has not been set yet.

### CODE REVIEW

**Comment by sirsquidness** [comment]
Nice one! Thanks :)

**Comment by Nicell** [comment]
Thanks for the package! It's been useful. Can we get an NPM pacakge release bump? @sirsquidness

**Comment by sirsquidness** [comment]
I was too slow.. was already doing that but had to reset my npm password _twice_ :grimacing: it's published now!

**Comment by Nicell** [comment]
Gotta say I was surprised to see you responded so quickly (no changes in 4 years!). Hmm new version still hasn't shown up for me yet.

**Comment by sirsquidness** [comment]
image

https://www.npmjs.com/package/srcds-log-receiver
it's definitely there. 

maybe some caches to bust in npm?

**Comment by Nicell** [comment]
image
Emptied my cache and reloaded. Must be an npm cache thing. I'll give it more time. Thanks again.

Edit: Just got the update!

**Comment by Nicell** [comment]
@sirsquidness you didn't build the TS, the files are still incorrect on your release.

**Comment by sirsquidness** [comment]
whoops... fixed now. I've set `package.json` to auto-build typescript files before publishing so I won't mess that up in the future!

https://www.npmjs.com/package/srcds-log-receiver/v/1.0.2

**Pull request merged**
